### ISSUE TITLE
Updating the .desktop file in releases

### ISSUE THREAD

**Issue by RDL-28** [NVIDIA/nvidia-settings#58]
Why isn't the /doc/nvidia-settings.desktop file updated in releases?

**Comment by aaronp24** [comment]
The change to add the translation missed the cutoff for the release 460 series of drivers, so I've been manually merging it to master on each release. The release tags are verbatim copies of the [release tarballs](https://download.nvidia.com/XFree86/nvidia-settings/) which is why they don't contain the new translation yet.

Once the next release series comes out then this translation entry should appear in the releases.
