### ISSUE TITLE
nvidia-settings does not save color settings

### ISSUE THREAD

**Issue by mnfdev** [NVIDIA/nvidia-settings#6]
"Color Correction" tab shows "Warning: The color settings have been changed ..." as soon as the current window is changed (for example, right under "Do you want to quit?" popup if you click [Quit] button after tuning Brightness), then the program resets to default color settings and writes RedBrightness/GreenBrightness/BlueBrightness=0.0000 to .nvidia-settings-rc.

Details: under openbox (Ubuntu 16.04 LXDE) "palette update" callback in ctkcolorcorrection.c is issued after every window change. Disabling g_signal_connect for callback_palette_update fixes the problem (testing patch: [17_avoid_reset_to_default_color_settings.zip](https://github.com/NVIDIA/nvidia-settings/files/614663/17_avoid_reset_to_default_color_settings.zip))

**Comment by aaronp24** [comment]
This looks like an openbox or LDXE problem. It seems to be resetting the color settings whenever the window focus changes, so nvidia-settings is detecting a real change to the gamma ramp initiated by software outside its control. Because it causes openbox to change the window focus, the "Really quit?" dialog appearing triggers the problem. You can work around it by disabling the quit dialog in the settings page.

**Comment by KestutisMa** [comment]
Same behavior on Arch Linux, KDE Plasma: brightness changes does auto-revert back after few seconds and message appears in "Warning: The color settings have been changed outside of nvidia-settings so the currenr slider values may be incorrect."

**Comment by KestutisMa** [comment]
Update: solved, Redshift control caused that.

**Comment by jean-tissot** [comment]
Hello,
I am on Ubuntu 20.04 and I have exactly the same problem.
I change brightness and contrast parameters in _nvidia-settings_, I apply the changes ("Confirm Current Changes" button), and it works, but a few tens of seconds later changes do auto-revert back and "Warning: The color settings have been changed outside of _nvidia-settings_ so the current slider values may be incorrect." message appears.
I suppose it's due to the "Night light" option (in the system parameters), but I would want to combine the two. But anyway, _nvidia-settings_ brightness and contrast parameters are reset on reboot, even if saved in the .nvidia-settings-rc file (and `nvidia-settings --load-config-only` doesn't charge these parameters from this file)
